---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

permissions: {}

jobs:
  workflows:
    uses: casse-boubou/ha-addon-workflows/.github/workflows/pr-labels.yaml@079177fd2a0c3e913c7c0b343c124e4f5ff3f82b # main
