---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  workflows:
    uses: casse-boubou/ha-addon-workflows/.github/workflows/release-drafter.yaml@079177fd2a0c3e913c7c0b343c124e4f5ff3f82b # main
